version: '3.8'

services:
  apivendas:
    image: postgres:16-alpine
    container_name: apivendas
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apivendas
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - D:/docker/apivendas:/var/lib/postgresql/data
